"""Tkinter app components."""

import typing
import tkinter as tk
import customtkinter as ctk
from freejay.messages import messages as mes
from freejay.messages import produce_consume as prodcon
from PIL import Image


class TkRoot(ctk.CTk, prodcon.Producer):
    """
    Tkinter app root.

    Extends the Tk toplevel widget with the producer interface.
    """

    pass


class TkComponent:
    """
    Tkinter app component.

    Intended to be extended by child classes, TkComponent provides functionality
    to create and send messages.

    The top level Tk widget (TkRoot) is registered at initialisation,
    which handles all messags dispatch.

    Currently supported message types:
        * Button
        * Key

    See methods docs for more details.
    """

    def __init__(self, tkroot: TkRoot, parent: typing.Any, source: mes.Source):
        """Construct TkComponent.

        Args:
            tkroot (TkRoot): Top level Tk widget.
            parent: parent Tk widget.
            source (mes.Source): TkComponent message source.
        """
        self.tkroot = tkroot
        self.parent = parent
        self.source = source

    def button_send(
        self,
        component: mes.Component,
        element: mes.Element,
        press_release: mes.PressRelease,
        data: typing.Optional[typing.Dict] = None,
    ) -> None:
        """Construct and send 'Button' message.

        Args:
            component (mes.Component): Message component
            element (mes.Element): Message Element
            press_release (mes.PressRelease): Press/Release
            data (dict, optional): data to send, defaults to None.
        """
        if not data:
            data = {}

        msg = mes.Message(
            sender=mes.Sender(
                source=self.source,
                trigger=mes.Trigger.BUTTON,
            ),
            content=mes.Button(
                press_release=press_release,
                component=component,
                element=element,
                data=data,
            ),
        )
        self.send_message(msg)

    def key_send(self, press_release: mes.PressRelease, tkevent: tk.Event) -> None:
        """Construct and send 'Key' message.

        Args:
            press_release (mes.PressRelease): Press/Release
            tkevent (tk.Event): Key event generated by Tkinter.
        """
        msg = mes.Message(
            sender=mes.Sender(
                source=self.source,
                trigger=mes.Trigger.KEY,
            ),
            content=mes.Key(press_release=press_release, sym=tkevent.keysym),
        )
        self.send_message(msg)

    def send_message(self, msg: mes.Message):
        """Send a message.

        Message is sent from the top level Tk widget.
        Args:
            msg (mes.Message): Message to send.
        """
        self.tkroot.send_message(msg)

    def make_button(
        self,
        parent,
        row: int,
        column: int,
        component: mes.Component,
        element: mes.Element,
        data_press: typing.Optional[typing.Dict] = None,
        data_release: typing.Optional[typing.Dict] = None,
        text: typing.Optional[str] = None,
        image_path: typing.Optional[str] = None,
        **kwargs
    ) -> ctk.CTkButton:
        """
        Make a button.

        Helper method to initialise and render a button that sends messages.

        Args:
            parent: parent Tk widget
            row (int): grid row for button position
            column (int): grid column for button position
            component (mes.Component): message component
            element (mes.Element): message element
            data_press (dict, optional): Data to send on press.
                Defaults to None.
            data_release (dict, optional): Data to send on release.
                Defaults to None.
            text (typing.Optional[str], optional): Button text. Defaults to None.
            image_path (typing.Optional[str], optional): Path to button icon.
                Defaults to None.
            **kwargs: Named arguments to pass to CTkButton initialiser.

        Returns:
            ctk.CTkButton: Button widget
        """
        # Use image if supplied
        if image_path:
            image = Image.open(image_path).resize((20, 20), Image.LANCZOS)
            photo_image = ctk.CTkImage(image)
        else:
            photo_image = None

        # Create button and configure grid positioning
        btn = ctk.CTkButton(parent, image=photo_image, text=text, **kwargs)
        btn.grid(row=row, column=column, padx=10, pady=10)

        # Add press/release bindings
        btn.bind(
            "<ButtonPress-1>",
            lambda event: self.button_send(
                component=component,
                element=element,
                press_release=mes.PressRelease.PRESS,
                data=data_press,
            ),
        )
        btn.bind(
            "<ButtonRelease-1>",
            lambda event: self.button_send(
                component=component,
                element=element,
                press_release=mes.PressRelease.RELEASE,
                data=data_release,
            ),
        )
        return btn


class TkMain(TkComponent):
    """
    Main application frame.

    Keybindings are registered here.
    """

    def __init__(
        self,
        tkroot: TkRoot,
        parent: typing.Any,
        source: mes.Source,
    ):
        """Construct TkMain.

        Args:
            tkroot (TkRoot): Top-level Tk widget.
            source (mes.Source): Source to use for messages.
        """
        super().__init__(tkroot=tkroot, parent=parent, source=source)
        self.frame = ctk.CTkFrame(self.parent)
        self.tkroot.bind(
            "<KeyPress>",
            lambda event: self.key_send(
                press_release=mes.PressRelease.PRESS, tkevent=event
            ),
        )
        self.tkroot.bind(
            "<KeyRelease>",
            lambda event: self.key_send(
                press_release=mes.PressRelease.RELEASE, tkevent=event
            ),
        )
