# This workflow will install Python dependencies, format, lint and run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'
    - name: Install system dependencies
      run: |
        sudo apt-get install -y libmpv1
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 mypy pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Format with black
      run: |
        black --diff --check $(git ls-files '*.py')
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics
    - name: Type checking with mypy
      run: |
        mypy $(git ls-files '*.py')
    - name: Test with pytest
      run: |
        pytest
